<SectionScreen>
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 40

        Label:
            text: "Выберите раздел"
            font_size: 28
            size_hint: (1, .2)

        BoxLayout:
            id: sections_box
            orientation: "vertical"
            spacing: 10

        Button:
            text: "<- Назад"
            size_hint_y: None
            height: 60
            on_press: app.root.curent = "main_screen"